### ISSUE TITLE
飞书应用推送出错

### ISSUE THREAD

**Issue by Arukassss** [nfe-w/aio-dynamic-push#14]
2024-05-09 16:12:13,209 - 1260736-MainThread -       _query_task.py[line: 61] - ERROR: 【bilibili】推送通道【推送通道_飞书自建应用】出错：Invalid URL '': No scheme supplied. Perhaps you meant https://?
Traceback (most recent call last):
  File "/home/aio-dynamic-push-master/query_task/_query_task.py", line 59, in push
    target_push_channel.push(title, content, jump_url, pic_url)
  File "/home/aio-dynamic-push-master/push_channel/feishu_apps.py", line 40, in push
    img_key = self._get_img_key(pic_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aio-dynamic-push-master/push_channel/feishu_apps.py", line 88, in _get_img_key
    response = requests.get(pic_url, verify=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

**Comment by nfe-w** [comment]
麻烦提供下用户id或者动态id，这个是动态图片下载时报错了，从日志上看是图片 url 缺少了 scheme（http:// 或 https://）

猜测可能是叔叔改了图片返回的格式

**Comment by Arukassss** [comment]
> 麻烦提供下用户id或者动态id，这个是动态图片下载时报错了，从日志上看是图片 url 缺少了 scheme（http:// 或 https://）
> 
> 猜测可能是叔叔改了图片返回的格式

2024-05-09 16:12:12,950 - 1260736-MainThread -    query_bilibili.py[line:312] -  INFO: 【B站-查询直播状态-B站】【机智大灯灯】开播了，准备推送：【歌势】可爱如我
2024-05-09 16:12:13,209 - 1260736-MainThread -       _query_task.py[line: 61] - ERROR: 【bilibili】推送通道【推送通道_飞书自建应用】出错：Invalid URL '': No scheme supplied. Perhaps you meant https://?
Traceback (most recent call last):
  File "/home/aio-dynamic-push-master/query_task/_query_task.py", line 59, in push
    target_push_channel.push(title, content, jump_url, pic_url)
  File "/home/aio-dynamic-push-master/push_channel/feishu_apps.py", line 40, in push
    img_key = self._get_img_key(pic_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aio-dynamic-push-master/push_channel/feishu_apps.py", line 88, in _get_img_key
    response = requests.get(pic_url, verify=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
完整的是这样的，是直播状态检测

**Comment by nfe-w** [comment]
无法复现，但我更新加了日志打印，可以重新拉镜像观察一下 ec559eb0c036e56d002521035828ac154aecd1cf
![image](https://github.com/nfe-w/aio-dynamic-push/assets/41944640/61289032-018c-4c8e-93e9-e94c8fa3d9cd)
<img width="635" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/151780d9-e1bf-4a02-9067-28dd5b019099">

**Comment by Arukassss** [comment]
发现后面的推送又正常了
![image](https://github.com/nfe-w/aio-dynamic-push/assets/89686441/4eb4bddf-e205-447b-812f-c78560273e36)
等加上webhook参数再重新拉取吧，顺便问一下小红书那个报错正常吗

**Comment by nfe-w** [comment]
小红书报错正常，偶发风控，不会影响后续查询
