### ISSUE TITLE
mblog的问题

### ISSUE THREAD

**Issue by Draudnaut** [nfe-w/aio-dynamic-push#2]
2024-03-07 17:55:57,712 - 49-MainThread -              main.py[line: 12] -  INFO: 开始初始化推送通道
2024-03-07 17:55:57,712 - 49-MainThread -              main.py[line: 19] -  INFO: 初始化推送通道: 推送通道_Gotify，通道类型: gotify
2024-03-07 17:55:57,712 - 49-MainThread -              main.py[line: 23] -  INFO: 初始化查询任务
2024-03-07 17:55:57,712 - 49-MainThread -              main.py[line: 28] -  INFO: 初始化查询任务: 任务_weibo，任务类型: weibo
2024-03-07 17:55:58,095 - 49-MainThread -       query_weibo.py[line: 29] - ERROR: 【微博-查询任务-任务_weibo】出错：'mblog'
Traceback (most recent call last):
  File "/app/query_task/query_weibo.py", line 27, in query
    self.query_dynamic(uid)
  File "/app/query_task/query_weibo.py", line 48, in query_dynamic
    if card["mblog"].get("isTop", None) == 1 or card["mblog"].get("mblogtype", None) == 2:
KeyError: 'mblog'
^CTraceback (most recent call last):
  File "/app/main.py", line 47, in <module>
    main()
  File "/app/main.py", line 43, in main
    init_query_task(query_task_config_list)
  File "/app/main.py", line 34, in init_query_task
    time.sleep(1)
KeyboardInterrupt

这个是缺少了字段导致的么

**Comment by Draudnaut** [comment]
我请求得到的字段在附件里面
[test.json](https://github.com/nfe-w/aio-dynamic-push/files/14522427/test.json)

**Comment by Draudnaut** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/16780642/ed698ba9-e007-4ec2-9062-2b021c45df1c)
好像知道了，这个地方如果有置顶图片的话会报bug，这个地方可以修改一下？看看我是否能开个PR？

**Comment by nfe-w** [comment]
感谢反馈，已修复

**Comment by Draudnaut** [comment]
卧槽这么快~ 感谢repo主~ 需要重新拉镜像么

**Comment by Draudnaut** [comment]
好像我本地docker拉不起来了（（
我是先git pull 然后docker删除本地镜像重新执行readme里面的docker run，但是重试了好几次都失败了

**Comment by nfe-w** [comment]
不需要拉git代码的，直接删除老镜像，拉新镜像即可
```sh
docker rmi nfew/aio-dynamic-push:latest
docker pull nfew/aio-dynamic-push:latest
```

**Comment by Draudnaut** [comment]
不好意思不太确定这个是否是停下来了，所以我把状态发上来了
![image](https://github.com/nfe-w/aio-dynamic-push/assets/16780642/3ceeb836-d08d-48fd-9712-4dd81f8193de)

这样的话应该是停下来了？
![image](https://github.com/nfe-w/aio-dynamic-push/assets/16780642/1999b7c7-9199-4863-bd67-e043a54a65ff)

**Comment by nfe-w** [comment]
看起来是停下来了，不过看起来你的容器有些多，可以如下查询：
```
docker ps -a | grep nfew
```

**Comment by Draudnaut** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/16780642/97f4897a-8dc7-429a-896a-bc76e4bbdaf3)

感谢感谢，我试了几次，每次都是刚启动然后就挂了。我用您给的命令更新过了

**Comment by Draudnaut** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/16780642/82bf758e-5596-482e-ba1e-07553713baff)
看了下是这个原因

**Comment by Draudnaut** [comment]
没事了没事了是我启动命令写错了，感谢作者~

**Comment by Draudnaut** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/16780642/b08a3b58-5e8d-4c3d-adec-28453027f4e0)
想多一句嘴，推送通道这么写应该是对的吧

**Comment by nfe-w** [comment]
看起来没问题，只要和通道名称一致即可

**Comment by Draudnaut** [comment]
好的，谢谢po主耐心指导~

NFE_W ***@***.***> 于2024年3月7日周四 19:53写道：
