### ISSUE TITLE
请教一下，抖音为什么报这个错误？

### ISSUE THREAD

**Issue by wwkk2580** [nfe-w/aio-dynamic-push#27]
```
2024-08-05 14:20:43,189 - 8-MainThread -              main.py[line: 12] -  INFO: 开始初始化推送通道
2024-08-05 14:20:43,189 - 8-MainThread -              main.py[line: 19] -  INFO: 初始化推送通道: 推送通道_钉钉机器人，通道类型: dingtalk_bot
2024-08-05 14:20:43,189 - 8-MainThread -              main.py[line: 19] -  INFO: 初始化推送通道: 推送通道_Email，通道类型: email
2024-08-05 14:20:43,189 - 8-MainThread -              main.py[line: 36] -  INFO: 初始化查询任务
2024-08-05 14:20:43,189 - 8-MainThread -              main.py[line: 41] -  INFO: 初始化查询任务: 任务_douyin，任务类型: douyin
2024-08-05 14:20:43,399 - 8-MainThread -      query_douyin.py[line: 80] -  INFO: 【抖音-生成ttwid-任务_douyin】成功：1%7C2Ora6IU1T3unrZAgvozieABaX1b4qkXOn0T4jkHMwgs%7C1722838843%7Ce0219febb545da860b828ca89a27daf332f46184d645128bc16e37407dfc6d0b
2024-08-05 14:20:43,399 - 8-MainThread -             cache.py[line:  7] -  INFO: [本地缓存]将: ttwid -> 1%7C2Ora6IU1T3unrZAgvozieABaX1b4qkXOn0T4jkHMwgs%7C1722838843%7Ce0219febb545da860b828ca89a27daf332f46184d645128bc16e37407dfc6d0b 存入缓存中
2024-08-05 14:20:43,681 - 8-MainThread -      query_douyin.py[line: 41] - ERROR: 【抖音-查询任务-任务_douyin】出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/query_task/query_douyin.py", line 36, in query
    self.query_dynamic(self.username_list[i], self.sec_uid_list[i])
  File "/app/query_task/query_douyin.py", line 93, in query_dynamic
    result = json.loads(str(response.content, "utf-8"))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-08-05 14:21:14,001 - 8-MainThread -      query_douyin.py[line: 41] - ERROR: 【抖音-查询任务-任务_douyin】出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/query_task/query_douyin.py", line 36, in query
    self.query_dynamic(self.username_list[i], self.sec_uid_list[i])
  File "/app/query_task/query_douyin.py", line 93, in query_dynamic
    result = json.loads(str(response.content, "utf-8"))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nfe-w** [comment]
不好意思抖音的视频检测目前坏了还不知道怎么修😰

**Comment by gavinliuisme** [comment]
https://github.com/saermart/DouyinLiveWebFetcher/blob/main/sign.js
看着是能解决的，作者可以试试

**Comment by nfe-w** [comment]
感谢提供参考，我周末看一下

**Comment by anwen-anyi** [comment]
> 感谢提供参考，我周末看一下

大佬怎么样了 现在有办法解决么~
