### ISSUE TITLE
抖音报错，无法检测直播等、

### ISSUE THREAD

**Issue by Xiunii** [nfe-w/aio-dynamic-push#29]
```
2024-08-14 11:37:35 2024-08-14 11:37:35,629 - 8-MainThread -      query_douyin.py[line: 48] - ERROR: 【抖音-获取签名】连接失败
2024-08-14 11:37:35 2024-08-14 11:37:35,817 - 8-MainThread -      query_douyin.py[line: 41] - ERROR: 【抖音-查询任务-任务_douyin】出错：Expecting value: line 1 column 1 (char 0)
2024-08-14 11:37:35 Traceback (most recent call last):
2024-08-14 11:37:35   File "/app/query_task/query_douyin.py", line 36, in query
2024-08-14 11:37:35     self.query_dynamic(self.username_list[i], self.sec_uid_list[i])
2024-08-14 11:37:35   File "/app/query_task/query_douyin.py", line 93, in query_dynamic
2024-08-14 11:37:35     result = json.loads(str(response.content, "utf-8"))
2024-08-14 11:37:35   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in `loads`
2024-08-14 11:37:35     return _default_decoder.decode(s)
2024-08-14 11:37:35   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
2024-08-14 11:37:35     obj, end = self.raw_decode(s, idx=_w(s, [0).end())](url)
2024-08-14 11:37:35   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
2024-08-14 11:37:35     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-08-14 11:37:35 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0
```

**Comment by Xiunii** [comment]
关闭动态检测后直播检测恢复正常
